import {
    listCountries,
    isArray,
    hasRequiredKeys,
    isLastIndex,
    stripHtml,
    stripIframeTags,
    isAndroid,
    isApple,
    isVoid,
    isResource,
    endSession,
    logError,
    mutatePlaces,
    debounce,
    deepGet,
    config,
    sum,
    getColorCode,
    unformat,
    checkCurrencyFormat,
    checkPrecision,
    defaults,
    toFixed,
    formatNumber,
    isObject,
    splitCountryCode,
} from './Helper';
import { calculatePercentage, haversine } from './Calculate';
import { syncDevice } from './Customer';
import { formatCurrency, capitalize, getStatusColors, truncateString } from './Format';
import { geocode, getCurrentLocation, getLocation } from './Geo';
import { translate } from './Localize';
import getCurrency from './get-currency';

export {
    listCountries,
    splitCountryCode,
    isArray,
    hasRequiredKeys,
    isLastIndex,
    stripHtml,
    stripIframeTags,
    isAndroid,
    isApple,
    isVoid,
    isResource,
    endSession,
    logError,
    calculatePercentage,
    haversine,
    syncDevice,
    formatCurrency,
    capitalize,
    getStatusColors,
    geocode,
    getCurrentLocation,
    getLocation,
    mutatePlaces,
    debounce,
    deepGet,
    config,
    sum,
    translate,
    getColorCode,
    getCurrency,
    truncateString,
    unformat,
    checkCurrencyFormat,
    checkPrecision,
    defaults,
    toFixed,
    formatNumber,
    isObject,
};
