/**
 * Points the app at the build's brand files.
 *
 * A client build keeps everything it owns in `brand/` (which this repository never
 * ships), so pulling a new release never touches a client file:
 *
 *   brand/storefront.brand.ts        branding (colors, typography, navigation, …)
 *   brand/storefront.extensions.ts   screen overrides, custom routes and tabs
 *   brand/translations/<locale>.json  copy added to or replacing the app's strings
 *   brand/fonts/*.ttf|otf|woff|woff2  font files named by their PostScript name
 *
 * Each one is optional. Missing files fall back to the templates at the repository
 * root (storefront.brand.ts, storefront.extensions.ts) or to nothing.
 *
 * The result is written to src/generated (git-ignored) as plain modules so every tool
 * resolves it the same way: Metro, webpack, Jest, tsc and the Tamagui compiler. It runs
 * from babel.config.js, postinstall and typecheck, and only rewrites a file whose
 * content changed so watchers don't loop.
 */
const fs = require('fs');
const path = require('path');

const FONT_EXTENSIONS = ['.ttf', '.otf', '.woff', '.woff2'];
const HEADER = '// Generated by scripts/link-brand.js from brand/ (or the root templates). Do not edit.\n';

function writeIfChanged(file, content) {
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === content) return false;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    return true;
}

const exists = (file) => fs.existsSync(file);
const firstExisting = (root, candidates) => candidates.find((candidate) => ['.ts', '.tsx', '.js'].some((ext) => exists(path.join(root, candidate + ext))));

function linkBrand(root = path.resolve(__dirname, '..')) {
    const brandDir = path.join(root, 'brand');
    const outDir = path.join(root, 'src', 'generated');
    const rel = (target) => {
        const relative = path.relative(outDir, path.join(root, target)).split(path.sep).join('/');
        return relative.startsWith('.') ? relative : `./${relative}`;
    };

    const brandConfig = firstExisting(root, ['brand/storefront.brand', 'storefront.brand']);
    const brandExtensions = firstExisting(root, ['brand/storefront.extensions', 'storefront.extensions']);
    const usesBrandDir = [brandConfig, brandExtensions].some((file) => file && file.startsWith('brand/'));

    writeIfChanged(
        path.join(outDir, 'brand-config.ts'),
        `${HEADER}import brandConfig from '${rel(brandConfig)}';\n\nexport const BRAND_DIR = ${usesBrandDir ? "'brand'" : 'null'};\nexport default brandConfig;\n`
    );
    writeIfChanged(path.join(outDir, 'brand-extensions.ts'), `${HEADER}import brandExtensions from '${rel(brandExtensions)}';\n\nexport default brandExtensions;\n`);

    // Translations: brand/translations/<locale>.json
    const translationsDir = path.join(brandDir, 'translations');
    const locales = exists(translationsDir)
        ? fs
              .readdirSync(translationsDir)
              .filter((file) => file.endsWith('.json'))
              .map((file) => file.replace(/\.json$/, ''))
              .filter((locale) => /^[a-zA-Z]{2,3}([_-][a-zA-Z0-9]{2,8})?$/.test(locale))
              .sort()
        : [];
    const translationImports = locales.map((locale, index) => `import t${index} from '${rel(`brand/translations/${locale}.json`)}';`).join('\n');
    const translationMap = locales.map((locale, index) => `    ${JSON.stringify(locale)}: t${index},`).join('\n');
    writeIfChanged(
        path.join(outDir, 'brand-translations.ts'),
        `${HEADER}${translationImports}${translationImports ? '\n\n' : ''}const brandTranslations: Record<string, Record<string, any>> = {\n${translationMap}${translationMap ? '\n' : ''}};\n\nexport default brandTranslations;\n`
    );

    // Fonts: brand/fonts/<PostScriptName>.<ext>. Native builds link the folder
    // (react-native.config.js); the web build imports each file for @font-face.
    const fontsDir = path.join(brandDir, 'fonts');
    const fonts = exists(fontsDir)
        ? fs
              .readdirSync(fontsDir)
              .filter((file) => FONT_EXTENSIONS.includes(path.extname(file).toLowerCase()))
              .sort()
        : [];
    const fontNames = fonts.map((file) => path.basename(file, path.extname(file)));
    writeIfChanged(
        path.join(outDir, 'brand-fonts.ts'),
        `${HEADER}/** Font files bundled from brand/fonts, by PostScript name. Native apps load them by name. */\nexport const brandFontFiles: Record<string, string | null> = {\n${fontNames.map((name) => `    ${JSON.stringify(name)}: null,`).join('\n')}${fontNames.length ? '\n' : ''}};\n`
    );
    const fontImports = fonts.map((file, index) => `import f${index} from '${rel(`brand/fonts/${file}`)}';`).join('\n');
    writeIfChanged(
        path.join(outDir, 'brand-fonts.web.ts'),
        `${HEADER}${fontImports}${fontImports ? '\n\n' : ''}/** Font files bundled from brand/fonts, by PostScript name, with their URLs on the web. */\nexport const brandFontFiles: Record<string, string | null> = {\n${fontNames.map((name, index) => `    ${JSON.stringify(name)}: f${index} as unknown as string,`).join('\n')}${fontNames.length ? '\n' : ''}};\n`
    );

    // Development env overrides: env.dev.json (git-ignored) at the repository root.
    const envOverrides = exists(path.join(root, 'env.dev.json'));
    writeIfChanged(
        path.join(outDir, 'env-overrides.ts'),
        envOverrides
            ? `${HEADER}import envOverrides from '${rel('env.dev.json')}';\n\nexport default envOverrides as Record<string, string>;\n`
            : `${HEADER}const envOverrides: Record<string, string> = {};\n\nexport default envOverrides;\n`
    );

    return { brandConfig, brandExtensions, locales, fonts: fontNames, envOverrides };
}

module.exports = { linkBrand };

if (require.main === module) {
    const result = linkBrand();
    console.log(`[link-brand] branding: ${result.brandConfig}, extensions: ${result.brandExtensions}, translations: ${result.locales.join(', ') || 'none'}, fonts: ${result.fonts.length}${result.envOverrides ? ', env.dev.json: yes' : ''}`);
}
