export default {
    APP_NAME: process.env.APP_NAME,
    APP_IDENTIFIER: process.env.APP_IDENTIFIER,
    APP_LINK_PREFIX: process.env.APP_LINK_PREFIX,
    SOCKETCLUSTER_HOST: process.env.SOCKETCLUSTER_HOST,
    SOCKETCLUSTER_PORT: process.env.SOCKETCLUSTER_PORT,
    SOCKETCLUSTER_SECURE: process.env.SOCKETCLUSTER_SECURE,
    FLEETBASE_HOST: process.env.FLEETBASE_HOST,
    FLEETBASE_KEY: process.env.FLEETBASE_KEY,
    STOREFRONT_KEY: process.env.STOREFRONT_KEY,
};
